### ISSUE TITLE
Automatically pluralize titles

### ISSUE THREAD

**Issue by CaddyDz** [CaddyDz/Isaac#14]
### In order to avoid repetition of localization strings: 

* install [Laravel Helpers](https://github.com/laravel/helpers) from [Packagist](https://packagist.org/packages/laravel/helpers)
* use the function [`str_plural`](https://laravel.com/docs/7.x/helpers#method-str-plural)
* Pluralize `explanation` title in [resources/views/explanations/explanation.blade.php Line 3](https://github.com/CaddyDz/Isaac/blob/master/resources/views/explanations/explanation.blade.php#L3)

**Comment by CaddyDz** [comment]
Pluralize the string directly into the Blade template like this

```html
@section('title', __(str_plural('explanation')))
```

**Comment by MEDANIS98** [comment]
Donee

**Comment by CaddyDz** [comment]
Thank you
